### ISSUE TITLE
Notifier throws an exception on Linux

### ISSUE THREAD

**Issue by martinslaner** [lcaron/opal#57]
Hi Laurent,

I was testing the Notifier feature of Opal, which seems to be exactly what I was looking for.
It works fine on Windows 7, but on Linux I found some problems.

Once the first notification is raised, it then vanishes after 5 seconds, as expected. But it seems
to dispose the Color 

I added some logging to org.mihalis.opal.notify.Notifier.createTitle

```
        final Color titleColor = colors.titleColor;
        System.out.println("Title Color = " + titleColor);
        titleLabel.setForeground(titleColor);
```

The first notification produces this output
    Title Color = Color {0, 0, 0}

After it is disposed, the second produces this output
    Title Color = Color {_DISPOSED_}

Which leads to this exception

```
Exception in thread "main" java.lang.IllegalArgumentException: Argument not valid
    at org.eclipse.swt.SWT.error(SWT.java:4422)
    at org.eclipse.swt.SWT.error(SWT.java:4356)
    at org.eclipse.swt.SWT.error(SWT.java:4327)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:476)
    at org.eclipse.swt.widgets.Control.setForeground(Control.java:4425)
    at org.mihalis.opal.notify.Notifier.createTitle(Notifier.java:142)
    at org.mihalis.opal.notify.Notifier.createNotificationWindow(Notifier.java:109)
    at org.mihalis.opal.notify.Notifier.notify(Notifier.java:91)
    at org.mihalis.opal.notify.Notifier.notify(Notifier.java:51)
    at org.mihalis.opal.notify.NotifierSnippet$1.handleEvent(NotifierSnippet.java:47)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
    at org.mihalis.opal.notify.NotifierSnippet.main(NotifierSnippet.java:82)
```

I managed to fix the problem simply by replacing the calls to
    `Display.getDefault().getSystemColor(SWT.COLOR_BLACK);`
by 
    `new Color(Display.getDefault(), 0, 0, 0);`

Here's the code

```
    static NotifierColors getColorsForTheme(final NotifierTheme theme) {
        final NotifierColors colors = new NotifierColors();
        switch (theme) {
            case BLUE_THEME:
                colors.textColor = new Color(Display.getDefault(), 4, 64, 140);
                colors.titleColor = new Color(Display.getDefault(), 0, 0, 0);
                colors.borderColor = new Color(Display.getDefault(), 153, 188, 232);
                colors.leftColor = new Color(Display.getDefault(), 210, 225, 244);
                colors.rightColor = new Color(Display.getDefault(), 182, 207, 238);
                break;
            case GRAY_THEME:
                colors.textColor = new Color(Display.getDefault(), 0, 0, 0);
                colors.titleColor = new Color(Display.getDefault(), 255, 20, 20);
                colors.borderColor = new Color(Display.getDefault(), 208, 208, 208);
                colors.leftColor = new Color(Display.getDefault(), 255, 255, 255);
                colors.rightColor = new Color(Display.getDefault(), 208, 208, 208);
                break;
            default:
                colors.textColor = new Color(Display.getDefault(), 0, 0, 0);
                colors.titleColor = new Color(Display.getDefault(), 0, 0, 0);
                colors.borderColor = new Color(Display.getDefault(), 218, 178, 85);
                colors.leftColor = new Color(Display.getDefault(), 220, 220, 160);
                colors.rightColor = new Color(Display.getDefault(), 255, 255, 191);
                break;
        }
        return colors;
    }

```

**Comment by lcaron** [comment]
Hi martin,

Thank you for your fix, it will we included in the next release !

Laurent
