### ISSUE TITLE
IndexOutOfBoundsException in the ImageSelector Control

### ISSUE THREAD

**Issue by vicenrico** [lcaron/opal#67]
When I switch very fast between images (while navigating with keys and clicking with the mouse), I get an IndexOutOfBoundsException.

`java.lang.IndexOutOfBoundsException: Index: -1, Size: 5
	at java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.util.LinkedList.get(Unknown Source)
	at org.mihalis.opal.imageSelector.ImageSelector.drawTitle(Unknown Source)
	at org.mihalis.opal.imageSelector.ImageSelector.paintControl(Unknown Source)
	at org.mihalis.opal.imageSelector.ImageSelector.access$000(Unknown Source)
	at org.mihalis.opal.imageSelector.ImageSelector$1.paintControl(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:231)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1593)`

I have to say that I've set "" for the images' titles.

**Comment by lcaron** [comment]
Problem fixed in release V1.0.6
